name: dotnet package

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/src
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore --configuration Release
      
      - name: Test with the dotnet CLI
        run: dotnet test --no-build -l trx --configuration Release

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: app/test/TestResults/**/*.trx
      
      - name: Create the package
        run: dotnet publish --no-build --configuration Release

      - name: Zip Folder
        working-directory: app/src/bin/Release/net9.0/publish/
        run: |
          rm -rf app.zip
          zip -r app.zip .

      - name: Upload app zip
        uses: actions/upload-artifact@v4
        with:
          name: app.zip
          path: app/src/bin/Release/net9.0/publish/app.zip
          if-no-files-found: error

